const assert=require('assert')
const {COURSE_TYPES,matchCourse,coursePicture}=require('./catalog')
assert.equal(COURSE_TYPES.length,21)
assert.equal(matchCourse('周三羽毛球训练').key,'badminton')
assert.equal(matchCourse('少儿钢琴启蒙').key,'piano')
assert.equal(matchCourse('机器人编程').key,'robot')
assert.equal(matchCourse('不在目录的新课程').key,'other')
assert.equal(coursePicture({name:'绘画',imageKey:'auto'}),'assets/courses/painting.png')
assert.equal(coursePicture({name:'任意课',imageKey:'tennis'}),'assets/courses/tennis.png')
assert.match(coursePicture({name:'任意课',imageKey:'custom',customImage:'data:image/png;base64,AA=='}),/^data:image/)
console.log('Passed: 8 course catalog assertions')
