const fs=require('fs'),p=require('path');const root=__dirname;
let app=fs.readFileSync(p.join(root,'app.js'),'utf8');
app=app.slice(app.indexOf('const esc='));
const render=`function render(){
const data=courses.map(c=>summarize(c));
document.querySelector('#summary').textContent=data.reduce((n,c)=>n+c.remaining,0)+'节剩余 · 已上'+data.reduce((n,c)=>n+c.completed,0)+'节';
document.querySelector('#courses').innerHTML=data.map(c=>\`<article class="course-row" aria-label="\${esc(c.name)}课程"><div class="day-label">星期\${c.weekdayLabel}</div><img class="course-art" src="assets/\${c.id==='english'?'english':'basketball'}.png" alt=""><div class="course-info"><h3>\${esc(c.name)}</h3><p class="time">\${c.startTime} – \${c.endTime}</p><div class="progress-caption">\${c.remaining} 节剩余</div><div class="progress" role="progressbar" aria-label="\${esc(c.name)}已上课时" aria-valuenow="\${c.completed}" aria-valuemin="0" aria-valuemax="\${c.total}"><span style="width:\${c.percent}%"></span></div><div class="course-meta"><span>已上\${c.completed} / 共\${c.total}节</span><span>\${c.next?'下次 '+c.next.date.slice(5).replace('-','月')+'日'+(c.next.skipped?' · 已请假':''):'本期已完成'}</span></div></div><div class="actions"><button class="settings" data-action="edit" data-id="\${c.id}"><img class="ui-icon" src="assets/gear.svg" alt="">设置</button><button class="primary" data-action="history" data-id="\${c.id}"><img class="ui-icon" src="assets/records.svg" alt="">上课记录</button>\${c.next?\`<button class="secondary" data-action="skip" data-id="\${c.id}" data-date="\${c.next.date}"><img class="ui-icon" src="assets/calendar.svg" alt="">\${c.next.skipped?'取消请假':'下次请假'}</button>\`:''}</div></article>\`).join('')
}
`;
app=app.slice(0,app.indexOf('function render()'))+render+app.slice(app.indexOf('function head('));
app=app.replace('aria-label="关闭">×','aria-label="关闭">关闭');
fs.writeFileSync(p.join(root,'app.js'),app);
fs.writeFileSync(p.join(root,'index.html'),'<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>兴趣课时本 · 周末探险队</title><link rel="stylesheet" href="assets/font.css"><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="adventure.css"></head><body><div class="adventure-page"><header><div class="brand">兴趣课时本</div><span class="local">本机保存</span></header><main><section class="intro"><h1>周末，一起长本领！</h1><p>每一个周末，都是新的探险！</p></section><section id="summary" class="summary" aria-label="课时概览"></section><section id="courses" class="courses" aria-label="周末课程"></section><footer>课程结束后自动扣除 1 节，请假不扣课。数据仅保存在当前浏览器。<br><span>首次使用，请在设置中确认开始日期及此前已上课时。</span></footer></main></div><dialog id="dialog" aria-labelledby="dialog-title"><div id="dialog-content"></div></dialog><div id="toast" role="status"></div><script src="schedule.js"></script><script src="app.js"></script></body></html>');
